### PR TITLE
fix for bug #36, damaged utf8 encoded dump

### PR DESCRIPTION
**Pull request by writch**

### CODE REVIEW

**Comment by writch** [comment]
The tests are failing due to newlines in scalars being retained when they aren't expected.

The tests are expecting truncation of the scalar at the first newline, it seems.

In my mind, if I store "Bob\n123 address\n92101" I expect to get it back.

Should I fix my expectations or the tests?

**Comment by karenetheridge** [comment]
> The tests are expecting truncation of the scalar at the first newline, it seems.

That's not what's happening. Take a closer look at the output:

```
t/31_local_tml.t ........ 1/?         
        #   Failed test 'YAML::Tiny round-trips correctly'
        #   at t/lib/TestBridge.pm line 165.
        #     Structures begin differing at:
        #          $got->[0]{j} = 'literal # content\nblock   # content\n'
        #     $expected->[0]{j} = 'literal # content
        #     block   # content
        #     '
        # GOT:
        # bless( [
        #   {
        #     'a' => 'b#content',
        #     'c' => 'd',
        #     'e' => [
        #       'f',
        #       'g# content'
        #     ],
        #     'h' => 'single',
        #     'h2' => 'single # content',
        #     'i' => 'double',
        #     'i2' => 'double # content',
        #     'j' => 'literal # content\\nblock   # content\\n',
        #     'k' => {},
        #     'l' => [],
        #     'm' => {
        #       'n' => 'o'
        #     }
        #   }
        # ], 'YAML::Tiny' )
        # 
        # WANTED:
        # bless( [
        #   {
        #     'a' => 'b#content',
        #     'c' => 'd',
        #     'e' => [
        #       'f',
        #       'g# content'
        #     ],
        #     'h' => 'single',
        #     'h2' => 'single # content',
        #     'i' => 'double',
        #     'i2' => 'double # content',
        #     'j' => 'literal # content
        # block   # content
        # ',
        #     'k' => {},
        #     'l' => [],
        #     'm' => {
        #       'n' => 'o'
        #     }
        #   }
        # ], 'YAML::Tiny' )
```

**Comment by writch** [comment]
I'm not sure we aren't seeing a bug somewhere else being reflected here.  Try this test code and look at some curious results.  This is all extrapolated from chanson's C2A9 example:

#!/usr/bin/perl -w

sub say{ print "$_[0]\n";}
use strict;
use YAML::Tiny;
my (@string);
$string[0] = "\xC2\xA9";
$string[1] = "\x{FB00}";
$string[2] = "\x{C2A9}";
$string[3] = "美国的私有退休金体制";
$string[4]  = "\x{7F8E}\x{56FD}\x{7684}\x{79C1}\x{6709}\x{9000}\x{4F11}\x{91D1}\x{4F53}\x{5236}";

my(%len);

for (@string)
{
   print "\nStock evaluation of $_\n";
   print "length: " . length($_) . "\n";
   {
      use bytes;
      print "byte length: " . length($_) . "\n";
   }
   print "valid utf8: " . utf8::valid($_) . "\n";
   {
     binmode STDOUT, ":utf8";
     print "utf evaluation of $_\n";
     print "length: " . length($_) . "\n";
     {
       use bytes;
       print "byte length: " . length($_) . "\n";
     }
     print "valid utf8: " . utf8::valid($_) . "\n";
     binmode STDOUT;
   }

}

$DB::single=2;
exit;

**Comment by writch** [comment]
Yes, it looks like some kind of bug.  The c2a9 issue is part of it.   The secondary definition of the same bytes is a red-herring.  

The initial \xC2\xA9 is being listed as valid utf8 with a length of 2, and a byte length of 2.  

The assignment of the string "美国的私有退休金体制" in code is being done as utf8, then when we switch to outfit print mode, it trashes the results.  The first char, "美" is represented by the bytes e7 be 8e, which is a valid utf8 char for code point 7F8E.  The 'length' is being misreported in non-byte mode.

The assignment of the same string using Unicode code point values shows the proper difference between chars and bytes.  It prints correctly.

**Comment by karenetheridge** [comment]
Your pasted code is unreadable -- you can have github format it properly either by indenting by four columns, or surrounding it by three backticks.

**Comment by miyagawa** [comment]
utf8::valid() is a highly internal function that tests an internal state of perl's scalar variable, and shouldn't used to check whether a byte is a valid utf8 sequence or not.

I think your understanding of perl's string handling has some shortcomings or, it's highly likely you're using the terminology in a different sense than what we're used to. I highly recommend you to take a look at the following posts to better understand the nature of them:

http://perlhacks.com/2013/08/unicode-perl/ (and comments)
http://weblog.bulknews.net/post/59317757811/perl-utf-8-crash-course

**Comment by writch** [comment]
Thanks, M.  Those links were very enlightening.  I'm sure someone somewhere will say, "That's not a bug, that's a feature."  In any event, that's a ghost we don't need to be chasing.

It took some time, and I'm not very satisfied with the Unicode regex 'grapheme' (\X) feature, nor the length, bytes::length feature, either.  Both of these return somewhat erratic results.  Try running the t/30_yaml_spec_tml.t up to 128.  The first time through _dump_scalar, length and bytes::length are 1, as the second time.  The third time, however, length is one, and bytes::length is two.

In any case, the code passes muster and doesn't trash utf8 data anymore.

**Comment by writch** [comment]
What I really expected @foo = /(\X)/ug to return on utf8 was not each individual char, even if they might be individually utf8.  I expected the graphemes (biggest, not smallest).

I expected something more like the output of this function, uni_split:

```
#!/usr/bin/perl -s

use strict;
our $stringin ||= '美国的私有退休金体制';

my @parts = uni_split($stringin);

sub uni_split {
    my($string) = @_;
    my(@retval);
    utf8::decode($string) or return;
    my @parts2 = split //, $string;
    for (@parts2) {
        utf8::encode($_);
        push @retval, $_;
    }
    return @retval;
}

print join "\n", @parts;
print "\n\n";
$DB::single = 2;
exit;
```

Often, I imagine greater, so I'm not ever surprised or depressed.  Still, it's not what I thought, at all.

**Comment by karenetheridge** [comment]
> What I really expected @foo = /(\X)/ug to return on utf8 was not each individual char.. I expected the graphemes

@writch If you `use utf8` in your example, then that's exactly what you get. Without `use utf8`, you are giving perl a series of octets, not unicode graphemes.

**Comment by writch** [comment]
Thank you, K.  I love having less misunderstanding in my thoughts.  You guys have cleared up a few years of fuzziness in my understanding of encoding in under a week.

Still, it seems counter-intuitive.  When the string is handed off, it's 11 wide characters, so perl has to do a utf8_decode to turn it into the 31 utf8 chars that it returns, and it's a Unicode regex matching pattern that was used. 

Having to explicity tell it that it's utf8 is silly, IMHO, but it does work.

I can do non-intuitive.  I just have trouble figuring it out.  Thanks again.

**Comment by dagolden** [comment]
> Having to explicity tell it that it's utf8 is silly, IMHO, but it does work.

Perl has no way of knowing the encoding of text in the source code file.  For legacy reasons, it defaults to Latin-1 (or possibly something else based on your locale settings).  The `use utf8` tells Perl that the source is encoded as UTF-8.

**Comment by karenetheridge** [comment]
I think we determined that this wasn't a bug in YAML::Tiny. Please open a new issue if there is something more to look at.

**Pull request closed without merging**
