### PR TITLE
Embedded newlines

### PR DESCRIPTION
**Pull request by vitahall**
I needed to embed newlines in a block literal scalar, so I have a patch and tests to do that. The main thing was to get the regex split at the top of `_read_scalar` not to eat blank lines; then the various read loops have to deal with them.

I worry that I misunderstand how you're supposed to handle leading spaces in the middle of those block literals. I don't try to catch those and let the existing code detect errors there.

This is my first pull request ever, so please be gentle. :)

### CODE REVIEW

**Comment by karenetheridge** [comment]
@ingydotnet can you please review?

**Comment by ingydotnet** [comment]
@karenetheridge looks good to me although I would add more tests. I'll merge this into branch PR/21 then I'll add some tests and make a PR on that and pass it back to you.

**Comment by vitahall** [comment]
What additional tests do you think are necessary? I could have a go adding them if you like.

**Comment by ingydotnet** [comment]
I pushed some test changes to:

https://github.com/Perl-Toolchain-Gang/YAML-Tiny/tree/PR/21

YAML doesn't need indentation spaces on blank lines in a literal scalar.

Any number of spaces on a line means same thing.

You could add tests for that too.

Sorry for the late reply. I'll be addressing more of this at the upcoming QA
Hackathon.

**Comment by ingydotnet** [comment]
I forgot to mention above that the code fails without the indentation. So currently we can't merge this. @vitahall have a go at fixing?

**Comment by vitahall** [comment]
I'm sorry, I haven't checked my notifications in a while. Oops. :)

I'll rebase to the current YAML::Tiny and take a look.

**Pull request closed without merging**
