### PR TITLE
Dumping for unknown stuff

### PR DESCRIPTION
**Pull request by polettix**
This change factors die-ing upon unknown object types (e.g. GLOBs or blessed objects) into a single method dumper_for_unknown().

The only behavior that is not backwards compatible is that the error message provided when trying to convert an unknown object at the top level is no more `Cannot serialize...` but `YAML::Tiny does not support...` as it was already the case when converting elements inside arrays and hash values. Performance shouldn't be impacted as well because the change only affects error conditions.

This allows anyway to sub-class YAML::Tiny (or just re-implement YAML::Tiny::dumper_for_unknown) and allow customizing the dumping. For example, it would allow easy support for the plethora of Boolean classes (JSON::PP::Boolean/Types::Serialiser::Boolean, JSON::XS::Boolean, Mojo::JSON::_Bool, etc.) with a simple subclassing.

It might be a handy transitional feature while you think about something for both supporting booleans and supporting generic serialization. There's anyway a high probability of rejection for this PR, but it's worth to revive the topics anyway (and it might give you hints/ideas).

### CODE REVIEW

**Comment by polettix** [comment]
I see that this was marked "needs review" some time ago. Can I help with the review process, e.g. providing further background or explanations?

**Comment by polettix** [comment]
Should I squash commits here too and push --force?

**Comment by polettix** [comment]
Rebased to the current `devel` branch in the main repository and squashed all commits into one.

I would kindly ask a feedback on this if possible, I'd like to stop using patched "graypan" versions :)

**Comment by karenetheridge** [comment]
@ingy?

**Comment by polettix** [comment]
Hi! Any news about this?

**Comment by polettix** [comment]
Hey... any chance you can take a look at this?

**Comment by polettix** [comment]
I eventually released [YAML::Dump](https://metacpan.org/pod/YAML::Dump), mostly based on code from YAML::Tiny.

I'm inclined to consider our communication a failure. I'd like to receive your feedback (if any) on how to try and improve (the kind of "do more of this" or "do less of this").

**Pull request closed without merging**
